[package]
edition = "2021"
name = "minimal-versions"
publish = false
version = "0.0.0"

[features]
futures = ["wasm-worker/futures"]
message = ["wasm-worker/message"]
worklet = ["wasm-worker/worklet"]

[dependencies]
wasm-worker = { path = ".." }
