[workspace]
members = ["", "core"]

[package]
edition = "2021"
name = "wasm-worker"
publish = false
version = "0.0.0"

[features]
blocking = ["dep:pollster"]
raw = []
registry = ["dep:vec_map"]

[dependencies]
futures-channel = "0.3"
futures-util = { version = "0.3", default-features = false }
js-sys = "0.3"
once_cell = { version = "1", default-features = false }
pin-project-lite = "0.2"
pollster = { version = "0.2", optional = true }
vec_map = { version = "0.8", optional = true }
wasm-bindgen = { version = "0.2", default-features = false }
wasm-bindgen-futures = "0.4"
wasm-worker-core = { version = "0.0", path = "core" }
web-sys = { version = "0.3", features = [
	"Blob",
	"BlobPropertyBag",
	"console",
	"DedicatedWorkerGlobalScope",
	"MessageEvent",
	"Url",
	"Worker",
] }

[dev-dependencies]
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
wasm-bindgen-test = "0.3"

[patch.crates-io]
# Waiting for PR's to be merged and a new version to be released.
# https://github.com/rustwasm/wasm-bindgen/pull/3168
# https://github.com/rustwasm/wasm-bindgen/pull/3247
# https://github.com/rustwasm/wasm-bindgen/pull/3252
# https://github.com/rustwasm/wasm-bindgen/pull/3279 (merged)
wasm-bindgen = { git = "https://github.com/daxpedda/wasm-bindgen", branch = "despair" }
