[package]
edition = "2021"
name = "wasm-worker"
publish = false
version = "0.0.0"

[features]
track = ["dep:vec_map"]

[dependencies]
futures-channel = { version = "0.3", default-features = false, features = ["alloc"] }
js-sys = "0.3"
pin-project-lite = "0.2"
vec_map = { version = "0.8", optional = true }
wasm-bindgen = { version = "0.2", default-features = false }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
	"Blob",
	"BlobPropertyBag",
	"console",
	"DedicatedWorkerGlobalScope",
	"ErrorEvent",
	"MessageEvent",
	"Url",
	"Worker",
] }

[dev-dependencies]
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
wasm-bindgen-test = "0.3"

[patch.crates-io]
# https://github.com/rustwasm/wasm-bindgen/pull/3032
# https://github.com/rustwasm/wasm-bindgen/pull/3084
# https://github.com/rustwasm/wasm-bindgen/pull/3092
wasm-bindgen = { git = "https://github.com/daxpedda/wasm-bindgen", branch = "despair" }
