[package]
edition = "2021"
name = "wasm-worker"
publish = false
version = "0.0.0"

[features]
futures = ["dep:futures-core"]
message = [
	"web-sys/AudioData",
	"web-sys/AudioDataInit",
	"web-sys/AudioSampleFormat",
	"web-sys/DomException",
	"web-sys/ImageBitmap",
	"web-sys/ImageData",
	"web-sys/MessageChannel",
	"web-sys/MessageEvent",
	"web-sys/MessagePort",
	"web-sys/OffscreenCanvas",
	"web-sys/ReadableStream",
	"web-sys/RtcDataChannel",
	"web-sys/RtcPeerConnection",
	"web-sys/TransformStream",
	"web-sys/VideoFrame",
	"web-sys/VideoFrameBufferInit",
	"web-sys/VideoPixelFormat",
	"web-sys/WritableStream",
]
worklet = [
	"web-sys/AbortController",
	"web-sys/AbortSignal",
	"web-sys/AudioWorklet",
	"web-sys/AudioWorkletGlobalScope",
	"web-sys/AudioWorkletNode",
	"web-sys/AudioWorkletNodeOptions",
	"web-sys/BaseAudioContext",
	"web-sys/OfflineAudioContext",
	"web-sys/RequestCache",
	"web-sys/RequestInit",
	"web-sys/Response",
]

[dependencies]
futures-core = { version = "0.3", optional = true, default-features = false }
js-sys = "0.3"
once_cell = "1"
wasm-bindgen = { version = "0.2", default-features = false }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
	"Blob",
	"BlobPropertyBag",
	"DedicatedWorkerGlobalScope",
	"Url",
	"Window",
	"Worker",
	"WorkerGlobalScope",
	"WorkerOptions",
	"WorkerType",
] }

[dev-dependencies]
console_error_panic_hook = "0.1"
futures-channel = { version = "0.3", default-features = false, features = ["alloc"] }
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
utf16_lit = "2"
wasm-bindgen-test = "0.3"
web-sys = { version = "0.3", features = [
	"AudioContext",
	"AudioDataCopyToOptions",
	"console",
	"RtcDataChannelState",
] }

[[example]]
name = "testing"
required-features = ["message", "worklet"]

[[test]]
name = "message_handler"
required-features = ["message"]

[[test]]
name = "no_import_support"
required-features = ["worklet"]
test = false

[[test]]
name = "no_module_support"
test = false

[[test]]
name = "race_has_image_bitmap_support"
required-features = ["message"]

[[test]]
name = "race_message_has_support"
required-features = ["message"]

[[test]]
name = "race_worklet_module_default"
required-features = ["worklet"]

[[test]]
name = "race_worklet_module_has_support"
required-features = ["worklet"]

[[test]]
name = "transfer"
required-features = ["message"]

[[test]]
name = "worklet"
required-features = ["worklet"]

[patch.crates-io]
# Waiting for PR's to be merged and a new version to be released.
# https://github.com/rustwasm/wasm-bindgen/pull/3168
# https://github.com/rustwasm/wasm-bindgen/pull/3247
# https://github.com/rustwasm/wasm-bindgen/pull/3279 (merged)
# https://github.com/rustwasm/wasm-bindgen/pull/3293 (merged)
# https://github.com/rustwasm/wasm-bindgen/pull/3296
# https://github.com/rustwasm/wasm-bindgen/pull/3299
# https://github.com/rustwasm/wasm-bindgen/pull/3302 (merged)
# https://github.com/rustwasm/wasm-bindgen/pull/3329 (merged)
js-sys = { git = "https://github.com/daxpedda/wasm-bindgen", branch = "despair" }
wasm-bindgen = { git = "https://github.com/daxpedda/wasm-bindgen", branch = "despair" }
wasm-bindgen-futures = { git = "https://github.com/daxpedda/wasm-bindgen", branch = "despair" }
wasm-bindgen-test = { git = "https://github.com/daxpedda/wasm-bindgen", branch = "despair" }
web-sys = { git = "https://github.com/daxpedda/wasm-bindgen", branch = "despair" }
